program ConsoleTest; 
{$APPTYPE CONSOLE}
uses
  SysUtils;

begin
  if (ParamCount = 2) and (ParamStr(1) = 'showvminfo') then
  begin
WriteLn('Name:            Sailfish OS Build Engine');
WriteLn('Groups:          /');
WriteLn('Guest OS:        Linux 2.6 / 3.x / 4.x (32-bit)');
WriteLn('UUID:            5bc88aa7-3372-4122-9d67-52b62310fdc4');
WriteLn('Config file:     C:\SailfishOS\mersdk\Sailfish OS Build Engine\Sailfish OS Build Engine.vbox');
WriteLn('Snapshot folder: C:\SailfishOS\mersdk\Sailfish OS Build Engine\Snapshots');
WriteLn('Log folder:      C:\SailfishOS\mersdk\Sailfish OS Build Engine\Logs');
WriteLn('Hardware UUID:   5bc88aa7-3372-4122-9d67-52b62310fdc4');
WriteLn('Memory size:     8192MB');
WriteLn('Page Fusion:     off');
WriteLn('VRAM size:       10MB');
WriteLn('CPU exec cap:    100%');
WriteLn('HPET:            off');
WriteLn('Chipset:         piix3');
WriteLn('Firmware:        BIOS');
WriteLn('Number of CPUs:  6');
WriteLn('PAE:             on');
WriteLn('Long Mode:       on');
WriteLn('Triple Fault Reset: off');
WriteLn('APIC:            on');
WriteLn('X2APIC:          off');
WriteLn('CPUID Portability Level: 0');
WriteLn('CPUID overrides: None');
WriteLn('Boot menu mode:  message and menu');
WriteLn('Boot Device (1): HardDisk');
WriteLn('Boot Device (2): Not Assigned');
WriteLn('Boot Device (3): Not Assigned');
WriteLn('Boot Device (4): Not Assigned');
WriteLn('ACPI:            on');
WriteLn('IOAPIC:          on');
WriteLn('BIOS APIC mode:  APIC');
WriteLn('Time offset:     0ms');
WriteLn('RTC:             local time');
WriteLn('Hardw. virt.ext: on');
WriteLn('Nested Paging:   on');
WriteLn('Large Pages:     on');
WriteLn('VT-x VPID:       on');
WriteLn('VT-x unr. exec.: on');
WriteLn('Paravirt. Provider: Default');
WriteLn('Effective Paravirt. Provider: KVM');
WriteLn('State:           running (since 2018-08-15T18:41:44.284000000)');
WriteLn('Monitor count:   1');
WriteLn('3D Acceleration: off');
WriteLn('2D Video Acceleration: off');
WriteLn('Teleporter Enabled: off');
WriteLn('Teleporter Port: 0');
WriteLn('Teleporter Address:');
WriteLn('Teleporter Password:');
WriteLn('Tracing Enabled: off');
WriteLn('Allow Tracing to Access VM: off');
WriteLn('Tracing Configuration:');
WriteLn('Autostart Enabled: off');
WriteLn('Autostart Delay: 0');
WriteLn('Default Frontend:');
WriteLn('Storage Controller Name (0):            SATA');
WriteLn('Storage Controller Type (0):            IntelAhci');
WriteLn('Storage Controller Instance Number (0): 0');
WriteLn('Storage Controller Max Port Count (0):  30');
WriteLn('Storage Controller Port Count (0):      2');
WriteLn('Storage Controller Bootable (0):        on');
WriteLn('SATA (1, 0): C:\SailfishOS\mersdk\mer.vdi (UUID: 9d8a6b7b-118a-4657-9d69-656ab6f3967f)');
WriteLn('NIC 1:           MAC: 080027F21001, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: virtio, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none');
WriteLn('NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)');
WriteLn('NIC 1 Rule(0):   name = guestssh, protocol = tcp, host ip = 127.0.0.1, host port = 2222, guest ip = , guest port = 22');
WriteLn('NIC 1 Rule(1):   name = guestwww, protocol = tcp, host ip = 127.0.0.1, host port = 8080, guest ip = , guest port = 9292');
WriteLn('NIC 2:           MAC: 08005A11F155, Attachment: Internal Network ''SailfishOS-SDK'', Cable connected: on, Trace: off (file: none), Type: virtio, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none');
WriteLn('NIC 3:           disabled');
WriteLn('NIC 4:           disabled');
WriteLn('NIC 5:           disabled');
WriteLn('NIC 6:           disabled');
WriteLn('NIC 7:           disabled');
WriteLn('NIC 8:           disabled');
WriteLn('Pointing Device: PS/2 Mouse');
WriteLn('Keyboard Device: PS/2 Keyboard');
WriteLn('UART 1:          disabled');
WriteLn('UART 2:          disabled');
WriteLn('UART 3:          disabled');
WriteLn('UART 4:          disabled');
WriteLn('LPT 1:           disabled');
WriteLn('LPT 2:           disabled');
WriteLn('Audio:           enabled (Driver: DSOUND, Controller: AC97, Codec: STAC9700)');
WriteLn('Audio playback:  disabled');
WriteLn('Audio capture: disabled');
WriteLn('Clipboard Mode:  disabled');
WriteLn('Drag and drop Mode: disabled');
WriteLn('Session name:    headless');
WriteLn('Video mode:      800x600x32 at 0,0 enabled');
WriteLn('VRDE:            disabled');
WriteLn('USB:             disabled');
WriteLn('EHCI:            disabled');
WriteLn('XHCI:            disabled');
WriteLn('');
WriteLn('USB Device Filters:');
WriteLn('');
WriteLn('<none>');
WriteLn('');
WriteLn('Available remote USB devices:');
WriteLn('');
WriteLn('<none>');
WriteLn('');
WriteLn('Currently Attached USB Devices:');
WriteLn('');
WriteLn('<none>');
WriteLn('');
WriteLn('Bandwidth groups:  <none>');
WriteLn('');
WriteLn('Shared folders:');
WriteLn('');
WriteLn('Name: ''home'', Host path: ''C:/Users/coderus'' (machine mapping), writable');
WriteLn('Name: ''targets'', Host path: ''C:\SailfishOS/mersdk/targets'' (machine mapping), writable');
WriteLn('Name: ''ssh'', Host path: ''C:\SailfishOS/mersdk/ssh'' (machine mapping), readonly');
WriteLn('Name: ''config'', Host path: ''C:\SailfishOS/vmshare'' (machine mapping), readonly');
WriteLn('Name: ''src1'', Host path: ''C:/Users/coderus'' (machine mapping), writable');
WriteLn('');
WriteLn('VRDE Connection:    not active');
WriteLn('Clients so far:     0');
WriteLn('');
WriteLn('Capturing:          not active');
WriteLn('Capture audio:      not active');
WriteLn('Capture screens:    0');
WriteLn('Capture file:       C:\SailfishOS\mersdk\Sailfish OS Build Engine\Sailfish OS Build Engine.webm');
WriteLn('Capture dimensions: 1024x768');
WriteLn('Capture rate:       512 kbps');
WriteLn('Capture FPS:        25');
WriteLn('Capture options:    ac_enabled=false');
WriteLn('');
WriteLn('Guest:');
WriteLn('');
WriteLn('Configured memory balloon size:      0 MB');
WriteLn('OS type:                             Linux26');
WriteLn('Additions run level:                 2');
WriteLn('Additions version:                   4.3.22 r98236');
WriteLn('');
WriteLn('');
WriteLn('Guest Facilities:');
WriteLn('');
WriteLn('Facility "VirtualBox Base Driver": active/running (last update: 2018/08/15 18:41:51 UTC)');
WriteLn('Facility "VirtualBox System Service": active/running (last update: 2018/08/15 18:41:51 UTC)');
WriteLn('Facility "Seamless Mode": not active (last update: 2018/08/15 18:41:51 UTC)');
WriteLn('Facility "Graphics Mode": not active (last update: 2018/08/15 18:41:51 UTC)');
WriteLn('');
WriteLn('Session name: headless');
WriteLn('');
  end;
  if (ParamCount = 3) then
  begin
WriteLn('name="Sailfish OS Build Engine"');
WriteLn('groups="/"');
WriteLn('ostype="Linux 2.6 / 3.x / 4.x (32-bit)"');
WriteLn('UUID="5bc88aa7-3372-4122-9d67-52b62310fdc4"');
WriteLn('CfgFile="C:\\SailfishOS\\mersdk\\Sailfish OS Build Engine\\Sailfish OS Build Engine.vbox"');
WriteLn('SnapFldr="C:\\SailfishOS\\mersdk\\Sailfish OS Build Engine\\Snapshots"');
WriteLn('LogFldr="C:\\SailfishOS\\mersdk\\Sailfish OS Build Engine\\Logs"');
WriteLn('hardwareuuid="5bc88aa7-3372-4122-9d67-52b62310fdc4"');
WriteLn('memory=8192');
WriteLn('pagefusion="off"');
WriteLn('vram=10');
WriteLn('cpuexecutioncap=100');
WriteLn('hpet="off"');
WriteLn('chipset="piix3"');
WriteLn('firmware="BIOS"');
WriteLn('cpus=6');
WriteLn('pae="on"');
WriteLn('longmode="on"');
WriteLn('triplefaultreset="off"');
WriteLn('apic="on"');
WriteLn('x2apic="off"');
WriteLn('cpuid-portability-level=0');
WriteLn('bootmenu="messageandmenu"');
WriteLn('boot1="disk"');
WriteLn('boot2="none"');
WriteLn('boot3="none"');
WriteLn('boot4="none"');
WriteLn('acpi="on"');
WriteLn('ioapic="on"');
WriteLn('biosapic="apic"');
WriteLn('biossystemtimeoffset=0');
WriteLn('rtcuseutc="off"');
WriteLn('hwvirtex="on"');
WriteLn('nestedpaging="on"');
WriteLn('largepages="on"');
WriteLn('vtxvpid="on"');
WriteLn('vtxux="on"');
WriteLn('paravirtprovider="default"');
WriteLn('effparavirtprovider="kvm"');
WriteLn('VMState="running"');
WriteLn('VMStateChangeTime="2018-08-15T18:41:44.284000000"');
WriteLn('monitorcount=1');
WriteLn('accelerate3d="off"');
WriteLn('accelerate2dvideo="off"');
WriteLn('teleporterenabled="off"');
WriteLn('teleporterport=0');
WriteLn('teleporteraddress=""');
WriteLn('teleporterpassword=""');
WriteLn('tracing-enabled="off"');
WriteLn('tracing-allow-vm-access="off"');
WriteLn('tracing-config=""');
WriteLn('autostart-enabled="off"');
WriteLn('autostart-delay=0');
WriteLn('defaultfrontend=""');
WriteLn('storagecontrollername0="SATA"');
WriteLn('storagecontrollertype0="IntelAhci"');
WriteLn('storagecontrollerinstance0="0"');
WriteLn('storagecontrollermaxportcount0="30"');
WriteLn('storagecontrollerportcount0="2"');
WriteLn('storagecontrollerbootable0="on"');
WriteLn('"SATA-0-0"="none"');
WriteLn('"SATA-1-0"="C:\SailfishOS\mersdk\mer.vdi"');
WriteLn('"SATA-ImageUUID-1-0"="9d8a6b7b-118a-4657-9d69-656ab6f3967f"');
WriteLn('natnet1="nat"');
WriteLn('macaddress1="080027F21001"');
WriteLn('cableconnected1="on"');
WriteLn('nic1="nat"');
WriteLn('nictype1="virtio"');
WriteLn('nicspeed1="0"');
WriteLn('mtu="0"');
WriteLn('sockSnd="64"');
WriteLn('sockRcv="64"');
WriteLn('tcpWndSnd="64"');
WriteLn('tcpWndRcv="64"');
WriteLn('Forwarding(0)="guestssh,tcp,127.0.0.1,2222,,22"');
WriteLn('Forwarding(1)="guestwww,tcp,127.0.0.1,8080,,9292"');
WriteLn('intnet2="SailfishOS-SDK"');
WriteLn('macaddress2="08005A11F155"');
WriteLn('cableconnected2="on"');
WriteLn('nic2="intnet"');
WriteLn('nictype2="virtio"');
WriteLn('nicspeed2="0"');
WriteLn('nic3="none"');
WriteLn('nic4="none"');
WriteLn('nic5="none"');
WriteLn('nic6="none"');
WriteLn('nic7="none"');
WriteLn('nic8="none"');
WriteLn('hidpointing="ps2mouse"');
WriteLn('hidkeyboard="ps2kbd"');
WriteLn('uart1="off"');
WriteLn('uart2="off"');
WriteLn('uart3="off"');
WriteLn('uart4="off"');
WriteLn('lpt1="off"');
WriteLn('lpt2="off"');
WriteLn('audio="dsound"');
WriteLn('audio_in="false"');
WriteLn('audio_out="false"');
WriteLn('clipboard="disabled"');
WriteLn('draganddrop="disabled"');
WriteLn('SessionName="headless"');
WriteLn('VideoMode="800,600,32"@0,0 1');
WriteLn('vrde="off"');
WriteLn('usb="off"');
WriteLn('ehci="off"');
WriteLn('xhci="off"');
WriteLn('SharedFolderNameMachineMapping1="home"');
WriteLn('SharedFolderPathMachineMapping1="C:/Users/coderus"');
WriteLn('SharedFolderNameMachineMapping2="targets"');
WriteLn('SharedFolderPathMachineMapping2="C:\SailfishOS/mersdk/targets"');
WriteLn('SharedFolderNameMachineMapping3="ssh"');
WriteLn('SharedFolderPathMachineMapping3="C:\SailfishOS/mersdk/ssh"');
WriteLn('SharedFolderNameMachineMapping4="config"');
WriteLn('SharedFolderPathMachineMapping4="C:\SailfishOS/vmshare"');
WriteLn('SharedFolderNameMachineMapping5="src1"');
WriteLn('SharedFolderPathMachineMapping5="C:/Users/coderus"');
WriteLn('VRDEActiveConnection="off"');
WriteLn('VRDEClients=0');
WriteLn('videocap="off"');
WriteLn('videocap_audio="off"');
WriteLn('videocapscreens=0');
WriteLn('videocapfile="C:\SailfishOS\mersdk\Sailfish OS Build Engine\Sailfish OS Build Engine.webm"');
WriteLn('videocapres=1024x768');
WriteLn('videocaprate=512');
WriteLn('videocapfps=25');
WriteLn('videocapopts=ac_enabled=false');
WriteLn('GuestMemoryBalloon=0');
WriteLn('GuestOSType="Linux26"');
WriteLn('GuestAdditionsRunLevel=2');
WriteLn('GuestAdditionsVersion="4.3.22 r98236"');
WriteLn('GuestAdditionsFacility_VirtualBox Base Driver=50,1534358511660');
WriteLn('GuestAdditionsFacility_VirtualBox System Service=50,1534358511859');
WriteLn('GuestAdditionsFacility_Seamless Mode=0,1534358511660');
WriteLn('GuestAdditionsFacility_Graphics Mode=0,1534358511660');
WriteLn('SessionType="headless"');
  end;
end.
